name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker login -u ${{secrets.dockerUser}} -p ${{secrets.dockerPass}}

      - name: build docker images
        run: docker build -t kaxun/warmhands .

      - name: publish image to docker hub
        run: docker push kaxun/warmhands:latest

 deploy:
   needs: build
   runs-on: self-hosted
   steps:
     - name: pull images from docker hub
       run: docker pull kaxun/warmhands:latest
     - name: run docker container
       run: docker run -d -p 5173:5173 --name warmhands-app-container




 
