name: CI/CD Pipeline

on:
  push:
    branches:
      - kasun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.dockerPass }}" | docker login -u "${{ secrets.dockerUser }}" --password-stdin

      - name: Build Docker image
        run: docker build -t kaxun/warmhands:latest .

      - name: Publish Docker image to Docker Hub
        run: docker push kaxun/warmhands:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull kaxun/warmhands:latest

      - name: Run Docker container
        run: docker run -d -p 5173:5173 --name warmhands-app-container kaxun/warmhands:latest