version: '3.8'

name: CI/CD Pipeline

on:
  push:
    branches:
      - kasun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=3.8  # Specify a stable version
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        shell: bash

      - name: Login to Docker Hub
        run: echo "${{ secrets.dockerPass }}" | docker login -u "${{ secrets.dockerUser }}" --password-stdin

      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose build
          docker-compose push

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2  # Specify a stable version
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        shell: bash

      - name: Login to Docker Hub
        run: echo "${{ secrets.dockerPass }}" | docker login -u "${{ secrets.dockerUser }}" --password-stdin

      - name: Pull and deploy services with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d
