name: CI/CD Pipeline

on:
  push:
    branches:
      - kasun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common
          
          # Add Docker’s official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          # Add Docker’s official repository
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          DOCKER_COMPOSE_VERSION=1.29.2  # Specify a stable version
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify the installation
        shell: bash

      - name: Login to Docker Hub
        run: echo "${{ secrets.dockerPass }}" | docker login -u "${{ secrets.dockerUser }}" --password-stdin

      - name: Build and push Docker images with Docker Compose
        run: docker build -t kaxun/warmhands:v1
          
      - name: Publish Docker image to Docker Hub
        run: docker push kaxun/warmhands:v1

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common
          
          # Add Docker’s official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          # Add Docker’s official repository
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          DOCKER_COMPOSE_VERSION=1.29.2  # Specify a stable version
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify the installation
        shell: bash

      - name: Login to Docker Hub
        run: echo "${{ secrets.dockerPass }}" | docker login -u "${{ secrets.dockerUser }}" --password-stdin
      - name: Print Working Directory
        run: pwd

      - name: Pull and deploy services with Docker Compose
        run: |
          docker-compose -f docker-compose.yaml pull
          docker-compose -f docker-compose.yaml up -d

      - name: Validate Docker Compose Configuration
        run: docker-compose config
